spring.application.name=jpa-demo

# URL de conexión a PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5433/java-c5
spring.datasource.username=postgres
spring.datasource.password=admin123

# opcional: mostrar las consultas SQL en la consola
spring.jpa.show-sql=true