spring.application.name=relaciones_empleado_dpto

spring.datasource.url = jdbc:postgresql://localhost:5433/relaciones_empleado_dpto
spring.datasource.username = postgres
spring.datasource.password = admin123

spring.jpa.hibernate.ddl-auto = update
spring.jpa.show-sql = true